/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BudgetLimit = IDL.Record({
  'id' : IDL.Nat,
  'monthlyLimit' : IDL.Float64,
  'createdAt' : IDL.Int,
  'category' : IDL.Text,
});
export const Time = IDL.Int;
export const ClothingItem = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'photoUrl' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
});
export const Entry = IDL.Record({
  'id' : IDL.Nat,
  'entryType' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const Folder = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'timestamp' : Time,
});
export const Note = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'timestamp' : Time,
  'folderId' : IDL.Nat,
});
export const Outfit = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'photoUrl' : IDL.Text,
  'occasion' : IDL.Text,
  'timestamp' : Time,
});
export const Routine = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'timestamp' : Time,
  'timeOfDay' : IDL.Text,
});
export const User = IDL.Principal;
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'user' : User,
  'completed' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const PlannerDayOutfit = IDL.Record({
  'outfitId' : IDL.Nat,
  'date' : IDL.Text,
});
export const RoutineCompletion = IDL.Record({
  'date' : IDL.Text,
  'completedRoutineIds' : IDL.Vec(IDL.Nat),
});
export const Preferences = IDL.Record({
  'geminiApiKey' : IDL.Text,
  'language' : IDL.Text,
  'darkMode' : IDL.Bool,
  'currency' : IDL.Text,
});
export const UserProfileView = IDL.Record({
  'tasks' : IDL.Vec(Task),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferences' : Preferences,
  'registrationTime' : Time,
  'finances' : IDL.Vec(Entry),
});
export const FinanceSummary = IDL.Record({
  'balance' : IDL.Float64,
  'totalIncome' : IDL.Float64,
  'totalExpenses' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBudgetLimit' : IDL.Func([IDL.Text, IDL.Float64], [BudgetLimit], []),
  'createClothingItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [ClothingItem],
      [],
    ),
  'createFinanceEntry' : IDL.Func(
      [IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [Entry],
      [],
    ),
  'createFolder' : IDL.Func([IDL.Text, IDL.Text], [Folder], []),
  'createNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [Note],
      [],
    ),
  'createOutfit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Outfit],
      [],
    ),
  'createRoutine' : IDL.Func([IDL.Text, IDL.Text], [Routine], []),
  'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Task], []),
  'deleteBudgetLimit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteClothingItem' : IDL.Func([IDL.Nat], [], []),
  'deleteEntry' : IDL.Func([IDL.Nat], [], []),
  'deleteFolder' : IDL.Func([IDL.Nat], [], []),
  'deleteNote' : IDL.Func([IDL.Nat], [], []),
  'deleteOutfit' : IDL.Func([IDL.Nat], [], []),
  'deletePlannerDayOutfit' : IDL.Func([IDL.Text], [], []),
  'deleteRoutine' : IDL.Func([IDL.Nat], [], []),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'ensureUserRegistered' : IDL.Func([], [IDL.Bool], []),
  'getAllBudgetLimits' : IDL.Func([], [IDL.Vec(BudgetLimit)], ['query']),
  'getAllClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
  'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
  'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllOutfits' : IDL.Func([], [IDL.Vec(Outfit)], ['query']),
  'getAllPlannerDayOutfits' : IDL.Func(
      [],
      [IDL.Vec(PlannerDayOutfit)],
      ['query'],
    ),
  'getAllRoutineCompletions' : IDL.Func(
      [],
      [IDL.Vec(RoutineCompletion)],
      ['query'],
    ),
  'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfileView)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPlannerDayOutfit' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(PlannerDayOutfit)],
      ['query'],
    ),
  'getRoutineCompletion' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RoutineCompletion)],
      ['query'],
    ),
  'getSummary' : IDL.Func([], [FinanceSummary], ['query']),
  'getUserGymState' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfileView)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listEntriesByType' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
  'listTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
  'registerCaller' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
  'saveUserGymState' : IDL.Func([IDL.Text], [], []),
  'setPlannerDayOutfit' : IDL.Func([IDL.Text, IDL.Nat], [PlannerDayOutfit], []),
  'setRoutineCompletion' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Nat)],
      [RoutineCompletion],
      [],
    ),
  'updateBudgetLimit' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64],
      [IDL.Opt(BudgetLimit)],
      [],
    ),
  'updateClothingItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [ClothingItem],
      [],
    ),
  'updateNote' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
      [Note],
      [],
    ),
  'updateOutfit' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Outfit],
      [],
    ),
  'updatePreferences' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateRoutine' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Routine], []),
  'updateTask' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Bool], [Task], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BudgetLimit = IDL.Record({
    'id' : IDL.Nat,
    'monthlyLimit' : IDL.Float64,
    'createdAt' : IDL.Int,
    'category' : IDL.Text,
  });
  const Time = IDL.Int;
  const ClothingItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'photoUrl' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
  });
  const Entry = IDL.Record({
    'id' : IDL.Nat,
    'entryType' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const Folder = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'timestamp' : Time,
  });
  const Note = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'timestamp' : Time,
    'folderId' : IDL.Nat,
  });
  const Outfit = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'photoUrl' : IDL.Text,
    'occasion' : IDL.Text,
    'timestamp' : Time,
  });
  const Routine = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'timestamp' : Time,
    'timeOfDay' : IDL.Text,
  });
  const User = IDL.Principal;
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'user' : User,
    'completed' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const PlannerDayOutfit = IDL.Record({
    'outfitId' : IDL.Nat,
    'date' : IDL.Text,
  });
  const RoutineCompletion = IDL.Record({
    'date' : IDL.Text,
    'completedRoutineIds' : IDL.Vec(IDL.Nat),
  });
  const Preferences = IDL.Record({
    'geminiApiKey' : IDL.Text,
    'language' : IDL.Text,
    'darkMode' : IDL.Bool,
    'currency' : IDL.Text,
  });
  const UserProfileView = IDL.Record({
    'tasks' : IDL.Vec(Task),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferences' : Preferences,
    'registrationTime' : Time,
    'finances' : IDL.Vec(Entry),
  });
  const FinanceSummary = IDL.Record({
    'balance' : IDL.Float64,
    'totalIncome' : IDL.Float64,
    'totalExpenses' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBudgetLimit' : IDL.Func([IDL.Text, IDL.Float64], [BudgetLimit], []),
    'createClothingItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ClothingItem],
        [],
      ),
    'createFinanceEntry' : IDL.Func(
        [IDL.Float64, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [Entry],
        [],
      ),
    'createFolder' : IDL.Func([IDL.Text, IDL.Text], [Folder], []),
    'createNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [Note],
        [],
      ),
    'createOutfit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Outfit],
        [],
      ),
    'createRoutine' : IDL.Func([IDL.Text, IDL.Text], [Routine], []),
    'createTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Task], []),
    'deleteBudgetLimit' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteClothingItem' : IDL.Func([IDL.Nat], [], []),
    'deleteEntry' : IDL.Func([IDL.Nat], [], []),
    'deleteFolder' : IDL.Func([IDL.Nat], [], []),
    'deleteNote' : IDL.Func([IDL.Nat], [], []),
    'deleteOutfit' : IDL.Func([IDL.Nat], [], []),
    'deletePlannerDayOutfit' : IDL.Func([IDL.Text], [], []),
    'deleteRoutine' : IDL.Func([IDL.Nat], [], []),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'ensureUserRegistered' : IDL.Func([], [IDL.Bool], []),
    'getAllBudgetLimits' : IDL.Func([], [IDL.Vec(BudgetLimit)], ['query']),
    'getAllClothingItems' : IDL.Func([], [IDL.Vec(ClothingItem)], ['query']),
    'getAllEntries' : IDL.Func([], [IDL.Vec(Entry)], ['query']),
    'getAllFolders' : IDL.Func([], [IDL.Vec(Folder)], ['query']),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllOutfits' : IDL.Func([], [IDL.Vec(Outfit)], ['query']),
    'getAllPlannerDayOutfits' : IDL.Func(
        [],
        [IDL.Vec(PlannerDayOutfit)],
        ['query'],
      ),
    'getAllRoutineCompletions' : IDL.Func(
        [],
        [IDL.Vec(RoutineCompletion)],
        ['query'],
      ),
    'getAllRoutines' : IDL.Func([], [IDL.Vec(Routine)], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPlannerDayOutfit' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(PlannerDayOutfit)],
        ['query'],
      ),
    'getRoutineCompletion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RoutineCompletion)],
        ['query'],
      ),
    'getSummary' : IDL.Func([], [FinanceSummary], ['query']),
    'getUserGymState' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfileView)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listEntriesByType' : IDL.Func([IDL.Text], [IDL.Vec(Entry)], ['query']),
    'listTasksByDate' : IDL.Func([IDL.Text], [IDL.Vec(Task)], ['query']),
    'registerCaller' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfileView], [], []),
    'saveUserGymState' : IDL.Func([IDL.Text], [], []),
    'setPlannerDayOutfit' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [PlannerDayOutfit],
        [],
      ),
    'setRoutineCompletion' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Nat)],
        [RoutineCompletion],
        [],
      ),
    'updateBudgetLimit' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64],
        [IDL.Opt(BudgetLimit)],
        [],
      ),
    'updateClothingItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [ClothingItem],
        [],
      ),
    'updateNote' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Vec(IDL.Text)],
        [Note],
        [],
      ),
    'updateOutfit' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Outfit],
        [],
      ),
    'updatePreferences' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateRoutine' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Routine], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Bool],
        [Task],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };