/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Note {
    id: bigint;
    title: string;
    body: string;
    tags: Array<string>;
    timestamp: Time;
    folderId: bigint;
}
export type Time = bigint;
export type User = Principal;
export interface Preferences {
    geminiApiKey: string;
    language: string;
    darkMode: boolean;
    currency: string;
}
export interface Task {
    id: bigint;
    title: string;
    date: string;
    user: User;
    completed: boolean;
    description: string;
    timestamp: Time;
}
export interface ClothingItem {
    id: bigint;
    name: string;
    photoUrl: string;
    timestamp: Time;
    category: string;
}
export interface PlannerDayOutfit {
    outfitId: bigint;
    date: string;
}
export interface RoutineCompletion {
    date: string;
    completedRoutineIds: Array<bigint>;
}
export interface Entry {
    id: bigint;
    entryType: string;
    date: string;
    description: string;
    timestamp: Time;
    category: string;
    amount: number;
}
export interface BudgetLimit {
    id: bigint;
    monthlyLimit: number;
    createdAt: bigint;
    category: string;
}
export interface UserProfileView {
    tasks: Array<Task>;
    name: string;
    email: string;
    preferences: Preferences;
    registrationTime: Time;
    finances: Array<Entry>;
}
export interface Outfit {
    id: bigint;
    name: string;
    tags: Array<string>;
    description: string;
    photoUrl: string;
    occasion: string;
    timestamp: Time;
}
export interface Folder {
    id: bigint;
    name: string;
    color: string;
    timestamp: Time;
}
export interface Routine {
    id: bigint;
    name: string;
    timestamp: Time;
    timeOfDay: string;
}
export interface FinanceSummary {
    balance: number;
    totalIncome: number;
    totalExpenses: number;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBudgetLimit(category: string, monthlyLimit: number): Promise<BudgetLimit>;
    createClothingItem(name: string, category: string, photoUrl: string): Promise<ClothingItem>;
    createFinanceEntry(amount: number, entryType: string, category: string, description: string, date: string): Promise<Entry>;
    createFolder(name: string, color: string): Promise<Folder>;
    createNote(title: string, body: string, folderId: bigint, tags: Array<string>): Promise<Note>;
    createOutfit(name: string, occasion: string, description: string, photoUrl: string, tags: Array<string>): Promise<Outfit>;
    createRoutine(name: string, timeOfDay: string): Promise<Routine>;
    createTask(title: string, description: string, date: string): Promise<Task>;
    deleteBudgetLimit(id: bigint): Promise<boolean>;
    deleteClothingItem(itemId: bigint): Promise<void>;
    deleteEntry(entryId: bigint): Promise<void>;
    deleteFolder(folderId: bigint): Promise<void>;
    deleteNote(noteId: bigint): Promise<void>;
    deleteOutfit(outfitId: bigint): Promise<void>;
    deletePlannerDayOutfit(date: string): Promise<void>;
    deleteRoutine(routineId: bigint): Promise<void>;
    deleteTask(taskId: bigint): Promise<void>;
    ensureUserRegistered(): Promise<boolean>;
    getAllBudgetLimits(): Promise<Array<BudgetLimit>>;
    getAllClothingItems(): Promise<Array<ClothingItem>>;
    getAllEntries(): Promise<Array<Entry>>;
    getAllFolders(): Promise<Array<Folder>>;
    getAllNotes(): Promise<Array<Note>>;
    getAllOutfits(): Promise<Array<Outfit>>;
    getAllPlannerDayOutfits(): Promise<Array<PlannerDayOutfit>>;
    getAllRoutineCompletions(): Promise<Array<RoutineCompletion>>;
    getAllRoutines(): Promise<Array<Routine>>;
    getAllTasks(): Promise<Array<Task>>;
    getCallerUserProfile(): Promise<UserProfileView | null>;
    getCallerUserRole(): Promise<UserRole>;
    getPlannerDayOutfit(date: string): Promise<PlannerDayOutfit | null>;
    getRoutineCompletion(date: string): Promise<RoutineCompletion | null>;
    getSummary(): Promise<FinanceSummary>;
    getUserGymState(): Promise<string | null>;
    getUserProfile(user: Principal): Promise<UserProfileView | null>;
    isCallerAdmin(): Promise<boolean>;
    listEntriesByType(entryType: string): Promise<Array<Entry>>;
    listTasksByDate(date: string): Promise<Array<Task>>;
    registerCaller(): Promise<void>;
    saveCallerUserProfile(profile: UserProfileView): Promise<void>;
    saveUserGymState(json: string): Promise<void>;
    setPlannerDayOutfit(date: string, outfitId: bigint): Promise<PlannerDayOutfit>;
    setRoutineCompletion(date: string, completedRoutineIds: Array<bigint>): Promise<RoutineCompletion>;
    updateBudgetLimit(id: bigint, category: string, monthlyLimit: number): Promise<BudgetLimit | null>;
    updateClothingItem(itemId: bigint, name: string, category: string, photoUrl: string): Promise<ClothingItem>;
    updateNote(noteId: bigint, title: string, body: string, folderId: bigint, tags: Array<string>): Promise<Note>;
    updateOutfit(outfitId: bigint, name: string, occasion: string, description: string, photoUrl: string, tags: Array<string>): Promise<Outfit>;
    updatePreferences(language: string, darkMode: boolean, geminiApiKey: string, currency: string): Promise<void>;
    updateRoutine(routineId: bigint, name: string, timeOfDay: string): Promise<Routine>;
    updateTask(taskId: bigint, title: string, description: string, completed: boolean): Promise<Task>;
}
import type { BudgetLimit as _BudgetLimit, PlannerDayOutfit as _PlannerDayOutfit, RoutineCompletion as _RoutineCompletion, UserProfileView as _UserProfileView, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBudgetLimit(arg0: string, arg1: number): Promise<BudgetLimit> {
        if (this.processError) {
            try {
                const result = await this.actor.createBudgetLimit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBudgetLimit(arg0, arg1);
            return result;
        }
    }
    async createClothingItem(arg0: string, arg1: string, arg2: string): Promise<ClothingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.createClothingItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClothingItem(arg0, arg1, arg2);
            return result;
        }
    }
    async createFinanceEntry(arg0: number, arg1: string, arg2: string, arg3: string, arg4: string): Promise<Entry> {
        if (this.processError) {
            try {
                const result = await this.actor.createFinanceEntry(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFinanceEntry(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createFolder(arg0: string, arg1: string): Promise<Folder> {
        if (this.processError) {
            try {
                const result = await this.actor.createFolder(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFolder(arg0, arg1);
            return result;
        }
    }
    async createNote(arg0: string, arg1: string, arg2: bigint, arg3: Array<string>): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.createNote(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNote(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createOutfit(arg0: string, arg1: string, arg2: string, arg3: string, arg4: Array<string>): Promise<Outfit> {
        if (this.processError) {
            try {
                const result = await this.actor.createOutfit(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOutfit(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createRoutine(arg0: string, arg1: string): Promise<Routine> {
        if (this.processError) {
            try {
                const result = await this.actor.createRoutine(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRoutine(arg0, arg1);
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: string): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteBudgetLimit(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBudgetLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBudgetLimit(arg0);
            return result;
        }
    }
    async deleteClothingItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClothingItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClothingItem(arg0);
            return result;
        }
    }
    async deleteEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEntry(arg0);
            return result;
        }
    }
    async deleteFolder(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFolder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFolder(arg0);
            return result;
        }
    }
    async deleteNote(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNote(arg0);
            return result;
        }
    }
    async deleteOutfit(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteOutfit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteOutfit(arg0);
            return result;
        }
    }
    async deletePlannerDayOutfit(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePlannerDayOutfit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePlannerDayOutfit(arg0);
            return result;
        }
    }
    async deleteRoutine(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRoutine(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRoutine(arg0);
            return result;
        }
    }
    async deleteTask(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async ensureUserRegistered(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.ensureUserRegistered();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.ensureUserRegistered();
            return result;
        }
    }
    async getAllBudgetLimits(): Promise<Array<BudgetLimit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBudgetLimits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBudgetLimits();
            return result;
        }
    }
    async getAllClothingItems(): Promise<Array<ClothingItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClothingItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClothingItems();
            return result;
        }
    }
    async getAllEntries(): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return result;
        }
    }
    async getAllFolders(): Promise<Array<Folder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFolders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFolders();
            return result;
        }
    }
    async getAllNotes(): Promise<Array<Note>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotes();
            return result;
        }
    }
    async getAllOutfits(): Promise<Array<Outfit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOutfits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOutfits();
            return result;
        }
    }
    async getAllPlannerDayOutfits(): Promise<Array<PlannerDayOutfit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlannerDayOutfits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlannerDayOutfits();
            return result;
        }
    }
    async getAllRoutineCompletions(): Promise<Array<RoutineCompletion>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoutineCompletions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoutineCompletions();
            return result;
        }
    }
    async getAllRoutines(): Promise<Array<Routine>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRoutines();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRoutines();
            return result;
        }
    }
    async getAllTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlannerDayOutfit(arg0: string): Promise<PlannerDayOutfit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlannerDayOutfit(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlannerDayOutfit(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRoutineCompletion(arg0: string): Promise<RoutineCompletion | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRoutineCompletion(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRoutineCompletion(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSummary(): Promise<FinanceSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSummary();
            return result;
        }
    }
    async getUserGymState(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserGymState();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserGymState();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfileView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listEntriesByType(arg0: string): Promise<Array<Entry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEntriesByType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEntriesByType(arg0);
            return result;
        }
    }
    async listTasksByDate(arg0: string): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.listTasksByDate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listTasksByDate(arg0);
            return result;
        }
    }
    async registerCaller(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCaller();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileView): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveUserGymState(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserGymState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserGymState(arg0);
            return result;
        }
    }
    async setPlannerDayOutfit(arg0: string, arg1: bigint): Promise<PlannerDayOutfit> {
        if (this.processError) {
            try {
                const result = await this.actor.setPlannerDayOutfit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPlannerDayOutfit(arg0, arg1);
            return result;
        }
    }
    async setRoutineCompletion(arg0: string, arg1: Array<bigint>): Promise<RoutineCompletion> {
        if (this.processError) {
            try {
                const result = await this.actor.setRoutineCompletion(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRoutineCompletion(arg0, arg1);
            return result;
        }
    }
    async updateBudgetLimit(arg0: bigint, arg1: string, arg2: number): Promise<BudgetLimit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBudgetLimit(arg0, arg1, arg2);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBudgetLimit(arg0, arg1, arg2);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateClothingItem(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<ClothingItem> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClothingItem(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClothingItem(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateNote(arg0: bigint, arg1: string, arg2: string, arg3: bigint, arg4: Array<string>): Promise<Note> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNote(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updateOutfit(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: Array<string>): Promise<Outfit> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOutfit(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOutfit(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updatePreferences(arg0: string, arg1: boolean, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePreferences(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePreferences(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateRoutine(arg0: bigint, arg1: string, arg2: string): Promise<Routine> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRoutine(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRoutine(arg0, arg1, arg2);
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: boolean): Promise<Task> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfileView]): UserProfileView | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlannerDayOutfit]): PlannerDayOutfit | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RoutineCompletion]): RoutineCompletion | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BudgetLimit]): BudgetLimit | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
